# Generated by Django 5.1.15 on 2026-09-16 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True)),
                ('segments', models.JSONField(blank=True, default=list, help_text='Timestamped segments [{start, end, text}]')),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='videos.videosource')),
            ],
        ),
    ]
