# Generated by Django 5.1.15 on 2026-09-16 19:41

import apps.exports.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField(default=0.0)),
                ('end_time', models.FloatField(default=0.0)),
                ('output_file', models.FileField(upload_to=apps.exports.models.clip_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.exports.models.thumb_upload_path)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('width', models.IntegerField(default=1080)),
                ('height', models.IntegerField(default=1920)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='ready', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='processing.processingjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
