# Generated by Django 5.1.15 on 2026-09-16 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip_duration', models.IntegerField(choices=[(15, '15 Seconds'), (30, '30 Seconds'), (45, '45 Seconds'), (60, '60 Seconds'), (90, '90 Seconds')], default=30)),
                ('clip_count', models.IntegerField(default=1)),
                ('start_time', models.FloatField(default=0.0)),
                ('end_time', models.FloatField(blank=True, null=True)),
                ('aspect_ratio', models.CharField(default='9:16', max_length=10)),
                ('crop_mode', models.CharField(choices=[('center', 'Center Crop (Fill 9:16)'), ('blur', 'Blurred Background'), ('fit', 'Fit with Letterbox/Pillarbox')], default='center', max_length=20)),
                ('caption_enabled', models.BooleanField(default=False)),
                ('caption_style', models.CharField(choices=[('classic', 'Classic White Subtitles'), ('bold_yellow', 'Bold Viral Yellow'), ('box', 'Subtitles with Box Background')], default='classic', max_length=50)),
                ('watermark_enabled', models.BooleanField(default=False)),
                ('watermark_text', models.CharField(blank=True, max_length=100)),
                ('audio_volume', models.FloatField(default=1.0, help_text='Audio volume multiplier')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress from 0 to 100')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to=settings.AUTH_USER_MODEL)),
                ('video_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='videos.videosource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
