# Generated by Django 5.1.15 on 2026-09-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_alter_processingjob_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='anti_copyright_enabled',
            field=models.BooleanField(default=True, help_text='Transformative filters to prevent automated Content ID matches'),
        ),
    ]
