# Generated by Django 5.1.15 on 2026-09-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_processingjob_anti_copyright_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='status_message',
            field=models.CharField(blank=True, default='In queue...', max_length=255),
        ),
    ]
