# Generated by Django 5.1.15 on 2026-09-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_processingjob_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='bg_music_url',
            field=models.CharField(blank=True, help_text='Optional YouTube or audio link for soft background music', max_length=500),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='bg_music_volume',
            field=models.FloatField(default=0.15, help_text='Background music volume (0.15 = 15% soft background music)'),
        ),
    ]
