# Generated by Django 5.1.15 on 2026-09-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_processingjob_bg_music_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingjob',
            name='bg_music_url',
        ),
        migrations.RemoveField(
            model_name='processingjob',
            name='bg_music_volume',
        ),
    ]
