# Generated by Django 5.1.15 on 2026-09-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_remove_bg_music_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingjob',
            name='clip_duration',
            field=models.IntegerField(choices=[(15, '15 Seconds'), (30, '30 Seconds ★ (Recommended)'), (45, '45 Seconds'), (60, '60 Seconds'), (90, '90 Seconds')], default=30),
        ),
    ]
